### PR TITLE
CLI

### LINKED ISSUE #18: Running Example In Repo Fails With Error
If you run the example per the contributing guide, you get this error after clicking the "play" button.

```shell
❯ node --import tsx --import ./loader.ts examples/example.ts --suspend
effection inspector@0.0.1 running at http://localhost:41000/live
suspending main, waiting for inspector to attach...
done
Error [ERR_INTERNAL_ASSERTION]: This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
Please open an issue with this stack trace at https://github.com/nodejs/node/issues

    at assert (node:internal/assert:11:11)
    at writableStreamDefaultControllerGetChunkSize (node:internal/webstreams/writablestream:1184:5)
    at writableStreamDefaultWriterWrite (node:internal/webstreams/writablestream:983:21)
    at WritableStreamDefaultWriter.write (node:internal/webstreams/writablestream:443:12)
    at EventStream._sendEvent (file:///Users/jacobbolda/dev/github/thefrontside/inspector/node_modules/.pnpm/h3@2.0.1-rc.14/node_modules/h3/dist/h3-Dol7UbDx.mjs:1533:22)
    at EventStream.push (file:///Users/jacobbolda/dev/github/thefrontside/inspector/node_modules/.pnpm/h3@2.0.1-rc.14/node_modules/h3/dist/h3-Dol7UbDx.mjs:1509:14)
    at Delimiter.operation (/Users/jacobbolda/dev/github/thefrontside/inspector/lib/sse-server.ts:61:28)
    at Generator.next (<anonymous>)
    at Delimiter.delimiter (/Users/jacobbolda/dev/github/thefrontside/inspector/node_modules/.pnpm/effection@4.1.0-alpha.5/node_modules/effection/src/lib/delimiter.ts:82:31)
    at delimiter.next (<anonymous>) {
  code: 'ERR_INTERNAL_ASSERTION'
}
```

### PR DESCRIPTION
**Pull request by jbolda**
# Motivation

We want to make it easier to work with, explore, and inspect. Command line interaction was already present, but without great DX. This CLI normalizes and provides a better entry point from the terminal perspective.

Closes #18.

# Approach

Match up using the client, and add helper commands.

# TODO

- [x] CLI with options to call and run commands with less args
- [x] child_process run presumes node, deno or bun based on running command

### CODE REVIEW

File: cli/config.ts [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+    base[current] = {
+      description: `/${current} API`,
+      ...object({
+        out: {
+          description: "write out the response to a file",
+          ...field(type("string | undefined"), field.default(undefined)),
+        },
+        host: {
+          description: "inspector base URL (overrides default)",
+          ...field(type("string"), field.default("http://localhost:41000")),
```
Comment (cowboyd) [inline cli/config.ts]: we should use a url schema.

File: cli/config.ts [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+          },
+          inspectRecord: {
+            description: "write inspector recording to the given file",
+            ...field(type("string | undefined"), field.default(undefined)),
+          },
+          host: {
+            description: "inspector base URL (overrides default)",
+            ...field(type("string"), field.default("http://localhost:41000")),
+          },
+          runtime: {
```
Comment (cowboyd) [inline cli/config.ts]: should we keep with the convention of using `--inspect-host` and `--inspect-runtime` so that we don't conflict with actual program arguments?

File: cli/index.ts [hunk 3]
```diff
@@ -0,0 +1,174 @@
...
+    yield* recordTask;
+  }
+
+  return status.code ?? 1;
+}
+
+function* recordNodeMapToFile(host: string, filePath: string): Operation<void> {
+  let values: unknown[] = [];
+  try {
+    let subscription = yield* invokeWithRetry("recordNodeMap", host);
```
Comment (cowboyd) [inline cli/index.ts]: Don't really wanna use band-aids? Why would be trying to connect without it being ready?

File: cli/index.ts [hunk 4]
```diff
@@ -0,0 +1,174 @@
...
+  }
+}
+
+// when executed as a script we delegate directly to Effection's `main`
+// which allows the code above to be imported for testing
+if (import.meta.url === `file://${process.argv[1]}`) {
+  await main(function* (args) {
+    yield* cliOp(args);
+  });
+}
```
Comment (cowboyd) [inline cli/index.ts]: we should just organize this differently so that there aren't any magic "gotchas."  Maybe split the things that we want to use as an export into their own file.

**Review by cowboyd — COMMENTED** [review]
Looking good! Any reason not to use configliere  here instead of the custom cli parser in `build-run-args.ts`? It is basically a second configuration schema that applies to the loader, but we can keep it in `loader.options.ts` and users would never see it. Just a private CLI. Would also let us use env vars and values later on too

File: cli/config.ts (hunk 2 above)
Comment (jbolda) [reply cli/config.ts]: Makes sense to me.

File: cli/index.ts (hunk 3 above)
Comment (jbolda) [reply cli/index.ts]: Open to suggestions here. I don't see an easy way to wait as we have to wait on the child_process to start and also the web service to be available.

Comment (cowboyd) [reply cli/index.ts]: Typically, you would have the process log something to STDERR.

Comment (cowboyd) [reply cli/index.ts]: In fact, the loader's output should actually all go to STDERR so as not to interfere with the process's STDOUT

Comment (jbolda) [reply cli/index.ts]: Ah, yea, forgot we discussed that, done.

Oh... so we should just read the log lines there? You don't think that will end up being brittle at all? We still need to deal with `run()` and are expecting the user to import and wire that.

File: cli/index.ts (hunk 4 above)
Comment (jbolda) [reply cli/index.ts]: I have pretty much split things out already; we can probably just remove that.

File: cli/index.ts (hunk 3 above)
Comment (cowboyd) [reply cli/index.ts]: But if they are importing run, then they won't be using our CLI, right?

Comment (jbolda) [reply cli/index.ts]: Possibly they will depending on how we decide to start the server, but let's kick those decisions down the road for now. We can always have a different command or something if we want to use the CLI. Swapped to not making the call until we are see it start up.

**Comment by jbolda** [comment]
Both configs are now in place. We should be all ready to go!

File: cli/index.ts [hunk 5]
```diff
@@ -0,0 +1,156 @@
...
+  const {
+    name,
+    config: { out, host },
+  } = config;
+  const argsList = [] as never[];
+  const handle = createSSEClient(inspector, { url: host });
+  if (!(name in handle.protocol.methods)) {
+    yield* log.error(`unknown command: ${name}`);
+    return 1;
+  }
```
Comment (cowboyd) [inline cli/index.ts:104]: How can this happen if the config is already validated?

**Review by cowboyd — APPROVED** [review]
